all:
	g++ -DLINUX -I. -I../../../../../../PJON/src -I../../../../../src -I../../../../../../ArduinoJson/src -I../../../../../../ReconnectingMqttClient/src GenericModuleMaster.cpp -o GenericModuleMaster -std=c++11
