all:
	g++ -DLINUX -I. -I../../../../../../PJON/src -I../../../../../src -I../../../../../../ArduinoJson/src -I../../../../../../ReconnectingMqttClient/src GenericModuleMasterHttp.cpp -o GenericModuleMasterHttp -std=c++11
