all:
	g++ -DLINUX -I. -I../../../../../../PJON/src -I../../../../../src -I../../../../../../ArduinoJson/src -I../../../../../../ReconnectingMqttClient/src GenericModuleMasterMqtt.cpp -o GenericModuleMasterMqtt -std=c++11
